### ISSUE TITLE
When signing in with Microsoft account: Not available on this device

### ISSUE THREAD

**Issue by trinityman** [bittner/skype#1]
The beta does not work when signing in with Microsoft account. It finally occurred to me to try my screen name (which means certain contacts won't show up), and it worked. Is there any chance that the Microsoft account can be supported?

**Comment by bittner** [comment]
Thanks for taking your time to compile an issue report.

I've tried to reproduce this issue, and I can see that when using a Microsoft account Skype Web causes the app to open up Ubuntu Touch's regular Web browser with the Microsoft Live login (i.e. it's leaving the Skype web app). Outside the app the message you see from Skype is "normal", the app overrides the user agent string so that Skype Web thinks we're a Linux desktop device.

**Workaround:** If you have a Skype user name logging in in the app will work normally.

I'll try to make the Microsoft login page stay inside the app.

## This Doesn't Fix the Issue?

If you think the analysis of the problem does not apply, please state more details:
- Which device are you using?
- Which version of Ubuntu Touch do you run?
- Please give an exact sequence of steps to reproduce the error.

**Comment by bittner** [comment]
New [version 0.4 released](https://uappexplorer.com/app/skype.peter-bittner) that fixes the issue.

Feel free to comment or reopen the issue if this is not fixed for you.
