### ISSUE TITLE
Make Skype for Web Calls on Ubuntu Phone

### ISSUE THREAD

**Issue by bartoszkosiorek** [bittner/skype#2]
I just read article about make call via webapp on Linux
http://www.omgubuntu.co.uk/2016/05/simple-hack-to-use-skype-web-linux

I'm wondering if such hack could be possible on Ubuntu Phone.

First guess is that following file needs to be changed:
https://github.com/bittner/skype/blob/master/skype.desktop

**Comment by bartoszkosiorek** [comment]
Here is the implemented skype.desktop which lie Skype Online that it is running on Edge browser
[Uploading skype.desktop.zip…]()

**Comment by bittner** [comment]
Thanks @gang65 for the hint.

I think setting the user agent string to Edge is obsolete now. Users of the app have reported (comments on the app in the Ubuntu Store) that voice calls are now working. Does it work for you too, finally?

I'd really prefer that Microsoft would detect and allow the Ubuntu Phone to run Skype for Web out of the box. The [current override](https://github.com/bittner/skype/blob/master/skype.desktop#L6) simply mimics a desktop computer, this is a minimal change. Though I see the Chromium version number is a bit low and could be updated ...

**Comment by bittner** [comment]
I've updated the README and the app description in the Ubuntu Store. I also updated the browser version in the user agent, only in the repository though, didn't make a release for that, because testing the change I didn't see any advantage or disadvantage of the change.

I'm closing this issue now as what you want to achieve seems to be working. Feel free to reopen it again if you feel there are still things left to do about the issue.
